name: quran_complete_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  pray_times: ^0.0.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  http: ^1.2.1
  arabic_numbers: ^1.0.0
  audioplayers: ^6.0.0
  flutter_settings_screens: ^0.3.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  geocoding: ^3.0.0
  geocode: ^1.0.3
  cloud_firestore: ^4.14.0
  share_plus: ^9.0.0
  firebase_auth: ^4.3.0
  email_validator: ^2.1.17

  url_launcher: ^6.1.5

  shared_preferences: ^2.2.3


  flutter_local_notifications: 17.1.2

  syncfusion_flutter_pdfviewer: ^25.2.5
  firebase_core: ^2.31.1







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
     - assets/images/
     - assets/sounds/azan.mp3
     - assets/sounds/hajj.pdf





  fonts:
  - family: Kitab-Regular
    fonts:
        - asset: fonts/Kitab-Regular.ttf

  - family: Kitab-Bold
    fonts:
        - asset: fonts/Kitab-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
