final Map<String, int> calculationMethods = {
  'Shia Ithna-Ansari': 0,
  'University of Islamic Sciences, Karachi': 1,
  'Islamic Society of North America': 2,
  'Muslim World League': 3,
  'Umm Al-Qura University, Makkah': 4,
  'Egyptian General Authority of Survey': 5,
  'Institute of Geophysics, University of Tehran': 7,
  'Gulf Region': 8,
  'Kuwait': 9,
  'Qatar': 10,
  'Majlis Ugama Islam Singapura, Singapore': 11,
  'Union Organization islamic de France': 12,
  'Diyanet İşleri Başkanlığı, Turkey': 13,
  'Spiritual Administration of Muslims of Russia': 14,
};
