// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBza0zUn8AXeSQpKAvYzdZSfYHkp21-L20',
    appId: '1:305792551171:web:67c7c65233e5ab5ad14136',
    messagingSenderId: '305792551171',
    projectId: 'quran-app-543b1',
    authDomain: 'quran-app-543b1.firebaseapp.com',
    storageBucket: 'quran-app-543b1.firebasestorage.app',
    measurementId: 'G-ZC75K6FRRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4VXl8OIuIRbhrp7T-Ypg0_H1zI_MEcvM',
    appId: '1:305792551171:android:7efcd328bf3d81b8d14136',
    messagingSenderId: '305792551171',
    projectId: 'quran-app-543b1',
    storageBucket: 'quran-app-543b1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-BduvDVJ9n8koUXPIXUl3bs0AJa3yxI',
    appId: '1:305792551171:ios:4b1479758b3975cbd14136',
    messagingSenderId: '305792551171',
    projectId: 'quran-app-543b1',
    storageBucket: 'quran-app-543b1.firebasestorage.app',
    iosBundleId: 'tunedtech.uk.quranCompleteUi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-BduvDVJ9n8koUXPIXUl3bs0AJa3yxI',
    appId: '1:305792551171:ios:7fcdded454920a80d14136',
    messagingSenderId: '305792551171',
    projectId: 'quran-app-543b1',
    storageBucket: 'quran-app-543b1.firebasestorage.app',
    iosBundleId: 'com.example.quranCompleteUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBza0zUn8AXeSQpKAvYzdZSfYHkp21-L20',
    appId: '1:305792551171:web:ed9bde64bdb78d96d14136',
    messagingSenderId: '305792551171',
    projectId: 'quran-app-543b1',
    authDomain: 'quran-app-543b1.firebaseapp.com',
    storageBucket: 'quran-app-543b1.firebasestorage.app',
    measurementId: 'G-JPXVQEYEKN',
  );
}
