// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNBSqwLB7KbhwuRN-Qho356juSx62EkI',
    appId: '1:497348146574:web:d9d4b9a918e16add5d60df',
    messagingSenderId: '497348146574',
    projectId: 'quran-41498',
    authDomain: 'quran-41498.firebaseapp.com',
    storageBucket: 'quran-41498.appspot.com',
    measurementId: 'G-D170C4GTPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7azQTuFQSUKKn_SiYoAxm2ChaT-yh8zg',
    appId: '1:497348146574:android:44d3879f1b57046d5d60df',
    messagingSenderId: '497348146574',
    projectId: 'quran-41498',
    storageBucket: 'quran-41498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFz6gcEJTGXPh8_G27nZjA3JDdJfWo6s',
    appId: '1:497348146574:ios:c64d59c367c353e85d60df',
    messagingSenderId: '497348146574',
    projectId: 'quran-41498',
    storageBucket: 'quran-41498.appspot.com',
    iosBundleId: 'com.example.quranCompleteUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFz6gcEJTGXPh8_G27nZjA3JDdJfWo6s',
    appId: '1:497348146574:ios:c64d59c367c353e85d60df',
    messagingSenderId: '497348146574',
    projectId: 'quran-41498',
    storageBucket: 'quran-41498.appspot.com',
    iosBundleId: 'com.example.quranCompleteUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQNBSqwLB7KbhwuRN-Qho356juSx62EkI',
    appId: '1:497348146574:web:3a91bc032e0cafda5d60df',
    messagingSenderId: '497348146574',
    projectId: 'quran-41498',
    authDomain: 'quran-41498.firebaseapp.com',
    storageBucket: 'quran-41498.appspot.com',
    measurementId: 'G-KZ4E5PMDPY',
  );
}
